messages:
  prefix: '&8(&9Moon&8)'
  restartIsComing: '%prefix% &cВнимание! Через %time% мин. будет осуществлен рестарт!'
  restartIsComing2: '%prefix% &cВнимание! Через %time2% сек. будет осуществлен рестарт!'
  restartStop: '%prefix% &cВнимание! Рестарт отменен!'
  noPerm: '&c>> У вас недостаточно прав!'
  restartFail: '%prefix% &c>> Нельзя запустить рестарт, он уже запущен!'
  restartFail2: '%prefix% &c>> Нельзя отменить рестарт, он не запущен!'
  help: '&e>> Доступные команды: &6/drestart start, stop'
  restartNoTime: '&c>> Укажите время до рестарта! /drestart start <минуты>'